# Generated by Django 4.1.4 on 2022-12-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.CharField(max_length=250)),
                ('imge', models.ImageField(upload_to='pics')),
                ('dec', models.TextField()),
            ],
        ),
    ]
